DELIMITER //

DROP PROCEDURE IF EXISTS `CorsList`;
CREATE DEFINER=`{RO}`@`{SERVER}` PROCEDURE `CorsList`()
 DETERMINISTIC
 SQL SECURITY INVOKER
 COMMENT 'Returns Cors list'
BEGIN
 SELECT * FROM `cors` ORDER BY `application`;
END//

DROP PROCEDURE IF EXISTS `CorsSearch`;
CREATE DEFINER=`{RO}`@`{SERVER}` PROCEDURE `CorsSearch`(IN `s` LONGTEXT)
 DETERMINISTIC
 SQL SECURITY INVOKER
 COMMENT 'Searches monitor records'
BEGIN
 SELECT * FROM `cors` WHERE `application` LIKE s OR `url` LIKE s OR `ip` LIKE s ORDER BY `application`;
END//

DROP PROCEDURE IF EXISTS `CorsAddUpdate`;
CREATE DEFINER=`{ADMIN}`@`{SERVER}` PROCEDURE `CorsAddUpdate`(IN `a` CHAR(12), IN `u` LONGTEXT, IN `i` LONGTEXT)
 DETERMINISTIC
 SQL SECURITY INVOKER
 COMMENT 'Add/Update cors'
BEGIN
 INSERT INTO `cors` (`application`, `url`, `ip`) VALUES (a, u, i) ON DUPLICATE KEY UPDATE `application`=a, `url`=u, `ip`=i;
 SELECT ROW_COUNT() AS affected;
END//

DROP PROCEDURE IF EXISTS `CorsUpdate`;
CREATE DEFINER=`{ADMIN}`@`{SERVER}` PROCEDURE `CorsUpdate`(IN `i` BIGINT, IN `a` CHAR(128), IN `u` LONGTEXT, IN `ip` LONGTEXT)
 DETERMINISTIC
 SQL SECURITY INVOKER
 COMMENT 'Add/Update cors'
BEGIN
 UPDATE `cors` SET `application`=a, `url`=u, `ip`=ip WHERE `id` = i;
 SELECT ROW_COUNT() AS affected;
END//

DROP PROCEDURE IF EXISTS `CorsDelete`;
CREATE DEFINER=`{ADMIN}`@`{SERVER}` PROCEDURE `CorsDelete`(IN `i` BIGINT)
 DETERMINISTIC
 SQL SECURITY INVOKER
 COMMENT 'Delete cors'
BEGIN
 DELETE FROM `cors` WHERE `id`=i LIMIT 1;
 SELECT ROW_COUNT() AS affected;
END//

DELIMITER ;
