<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MLIB-Inventory-Server RESTFul API') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headScript()->prependFile('https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js') ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> Marriott Library, University Of Utah. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
